name: Preview Deploy (Branches & PRs)

on:
  push:
    branches-ignore: [main]
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  preview:
    name: Deploy to Vercel (Preview)
    runs-on: ubuntu-latest
    concurrency:
      group: vercel-preview-${{ github.head_ref || github.ref }}
      cancel-in-progress: true
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20 LTS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Pull Vercel Environment (PREVIEW)
        run: npx vercel pull --yes --environment=preview --token=$VERCEL_TOKEN

      - name: Build with Vercel (Prebuilt)
        run: npx vercel build --token=$VERCEL_TOKEN

      - name: Deploy Prebuilt to Vercel (PREVIEW)
        run: npx vercel deploy --prebuilt --token=$VERCEL_TOKEN
